import { Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-rajdhani",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` ${rajdhani.variable} h-full antialiased`}
    >
      <body className={`${rajdhani.className} min-h-full flex flex-col`}>
        <header>
          <Navbar></Navbar>
        </header>
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
